/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as SetUpScheduleRouteImport } from './routes/set-up/schedule'
import { Route as SetUpExamDayRouteImport } from './routes/set-up/exam-day'
import { Route as SetUpAlarmRouteImport } from './routes/set-up/alarm'
import { Route as QuizClassIdRouteImport } from './routes/quiz/$classId'
import { Route as NotesUploadRouteImport } from './routes/notes/upload'

const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUpScheduleRoute = SetUpScheduleRouteImport.update({
  id: '/set-up/schedule',
  path: '/set-up/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUpExamDayRoute = SetUpExamDayRouteImport.update({
  id: '/set-up/exam-day',
  path: '/set-up/exam-day',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUpAlarmRoute = SetUpAlarmRouteImport.update({
  id: '/set-up/alarm',
  path: '/set-up/alarm',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizClassIdRoute = QuizClassIdRouteImport.update({
  id: '/quiz/$classId',
  path: '/quiz/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesUploadRoute = NotesUploadRouteImport.update({
  id: '/notes/upload',
  path: '/notes/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/setting': typeof SettingRoute
  '/notes/upload': typeof NotesUploadRoute
  '/quiz/$classId': typeof QuizClassIdRoute
  '/set-up/alarm': typeof SetUpAlarmRoute
  '/set-up/exam-day': typeof SetUpExamDayRoute
  '/set-up/schedule': typeof SetUpScheduleRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/setting': typeof SettingRoute
  '/notes/upload': typeof NotesUploadRoute
  '/quiz/$classId': typeof QuizClassIdRoute
  '/set-up/alarm': typeof SetUpAlarmRoute
  '/set-up/exam-day': typeof SetUpExamDayRoute
  '/set-up/schedule': typeof SetUpScheduleRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/setting': typeof SettingRoute
  '/notes/upload': typeof NotesUploadRoute
  '/quiz/$classId': typeof QuizClassIdRoute
  '/set-up/alarm': typeof SetUpAlarmRoute
  '/set-up/exam-day': typeof SetUpExamDayRoute
  '/set-up/schedule': typeof SetUpScheduleRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/setting'
    | '/notes/upload'
    | '/quiz/$classId'
    | '/set-up/alarm'
    | '/set-up/exam-day'
    | '/set-up/schedule'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/setting'
    | '/notes/upload'
    | '/quiz/$classId'
    | '/set-up/alarm'
    | '/set-up/exam-day'
    | '/set-up/schedule'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/setting'
    | '/notes/upload'
    | '/quiz/$classId'
    | '/set-up/alarm'
    | '/set-up/exam-day'
    | '/set-up/schedule'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  SettingRoute: typeof SettingRoute
  NotesUploadRoute: typeof NotesUploadRoute
  QuizClassIdRoute: typeof QuizClassIdRoute
  SetUpAlarmRoute: typeof SetUpAlarmRoute
  SetUpExamDayRoute: typeof SetUpExamDayRoute
  SetUpScheduleRoute: typeof SetUpScheduleRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-up/schedule': {
      id: '/set-up/schedule'
      path: '/set-up/schedule'
      fullPath: '/set-up/schedule'
      preLoaderRoute: typeof SetUpScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-up/exam-day': {
      id: '/set-up/exam-day'
      path: '/set-up/exam-day'
      fullPath: '/set-up/exam-day'
      preLoaderRoute: typeof SetUpExamDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-up/alarm': {
      id: '/set-up/alarm'
      path: '/set-up/alarm'
      fullPath: '/set-up/alarm'
      preLoaderRoute: typeof SetUpAlarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$classId': {
      id: '/quiz/$classId'
      path: '/quiz/$classId'
      fullPath: '/quiz/$classId'
      preLoaderRoute: typeof QuizClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/upload': {
      id: '/notes/upload'
      path: '/notes/upload'
      fullPath: '/notes/upload'
      preLoaderRoute: typeof NotesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  SettingRoute: SettingRoute,
  NotesUploadRoute: NotesUploadRoute,
  QuizClassIdRoute: QuizClassIdRoute,
  SetUpAlarmRoute: SetUpAlarmRoute,
  SetUpExamDayRoute: SetUpExamDayRoute,
  SetUpScheduleRoute: SetUpScheduleRoute,
  QuizIndexRoute: QuizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
